#!/usr/bin/env ruby
# frozen_string_literal: true

require 'create_rails_app'

begin
  exit CreateRailsApp::CLI.start(ARGV)
rescue StandardError => e
  warn "create-rails-app: #{e.message}"
  exit 1
end
